spring.application.name=accessmanager

# Puerto de la aplicación
server.port=8080

# Configuración básica para desarrollo local (por ahora apunta a una BD local ficticia)
spring.datasource.url=jdbc:mysql://localhost:3306/accessmanager_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=AtomG-S0ft

# Hibernate configuraciones
# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true